version: '3'
services: 
  db:
    image: mysql:8.0.23
    environment: 
      MYSQL_ROOT_PASSWORD: password
    volumes: 
      - ./mysql:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports: 
      - 3306:3306
  app:
    build: rails
    volumes: 
      - ./rails:/usr/src/app
    command: ["rails", "server", "-b", "0.0.0.0"]
    ports: 
      - 3000:3000
    depends_on:
      - db